<?php

namespace GDCalendar\Database\Migrations;

use GDCalendar\Models\Settings\Theme;
use GDCalendar\Models\Settings\ThemeSettings;

class CreateThemeSettingTable {

	public static function run(){

		global $wpdb;

	    $wpdb->query(
		    "CREATE TABLE IF NOT EXISTS " . $wpdb->prefix . "gdcalendarthemessettings(
                id int(11) unsigned NOT NULL AUTO_INCREMENT,
                theme_id int(11) unsigned NOT NULL,
                theme_type VARCHAR(255) NOT NULL,
                theme_option_key VARCHAR(255) NOT NULL,
                theme_option_value TEXT,
                PRIMARY KEY(id),
                FOREIGN KEY (theme_id) REFERENCES " . $wpdb->prefix . "gdcalendarthemes(id) ON DELETE CASCADE,
                UNIQUE KEY(theme_id, theme_option_key)
            ) ENGINE=InnoDB"
	    );

	    self::insertDefaultThemeSettings();
	}

	private static function insertDefaultThemeSettings(){

		global $wpdb;

		$rows = $wpdb->get_results('SELECT id FROM '.$wpdb->prefix.'gdcalendarthemessettings LIMIT 1');

		if(!empty($rows)){
			return;
		}

	    $defaultThemesOptions = array(

		    'Default Theme' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => 'f3822f',
			        'sidebar_current_date_bg_color' => 'f3822f',
  			        'sidebar_bg_color' => '333',
				    'sidebar_first_circle_bg_color' => '0f0',
				    'sidebar_second_circle_bg_color' => 'f0f',
				    'sidebar_third_circle_bg_color' => '00aeef',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => 'f3822f',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => 'f3822f',
    			    'datepicker_current_day_active_bg_color' => 'f3822f',
    			    'datepicker_current_day_selected_bg_color' => 'f1be84',
    			    'datepicker_button_bg_color' => 'f3822f',
			    ),
			    'Day' => array(
    			    'day_today_color' => 'f3822f',
    			    'day_event_first_border_left' => '00ff00',
    			    'day_event_second_border_left' => 'ff00ff',
    			    'day_event_third_border_left' => '00aeef',
    			    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'dbffdb',
				    'day_event_second_bg_color' => 'ffccff',
				    'day_event_third_bg_color' => 'cceffc',
			    ),
			    'Week' => array(
	    		    'week_current_day_bg_color' => 'f3822f',
    			    'week_number_color' => 'f3822f',
    			    'week_event_first_border_left' => '00ff00',
				    'week_event_second_border_left' => 'ff00ff',
				    'week_event_third_border_left' => '00aeef',
    			    'week_table_background_color' => 'ffffff',
		            'week_see_all_link_color' => 'f3822f',
    			    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'dbffdb',
				    'week_event_second_bg_color' => 'ffccff',
				    'week_event_third_bg_color' => 'cceffc',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => 'f3822f',
    			    'month_table_background_color' => 'ffffff',
    			    'month_table_weekend_columns_background_color' => 'f9f9f9',
      		        'month_see_all_link_color' => 'f3822f',
				    'month_first_circle_bg_color' => '0f0',
				    'month_second_circle_bg_color' => 'f0f',
				    'month_third_circle_bg_color' => '00aeef',
				    'month_event_first_bg_color' => 'dbffdb',
				    'month_event_second_bg_color' => 'ffccff',
				    'month_event_third_bg_color' => 'cceffc',
			    ),
			    'Year' => array(
  			        'year_current_date_bg_color' => 'f3822f',
    			    'year_title_color' => 'f3822f',
    			    'year_current_month_color' => 'f3822f',
    			    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => '0f0',
				    'year_second_circle_bg_color' => 'f0f',
				    'year_third_circle_bg_color' => '00aeef',
			    ),
		    ),
		    'Burgundy' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => 'a5173f',
				    'sidebar_current_date_bg_color' => 'a5173f',
				    'sidebar_bg_color' => '0b1c24',
				    'sidebar_first_circle_bg_color' => 'ef1c51',
				    'sidebar_second_circle_bg_color' => '1e0bab',
				    'sidebar_third_circle_bg_color' => '00aeef',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => 'a5173f',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => 'a5173f',
				    'datepicker_current_day_active_bg_color' => 'a5173f',
				    'datepicker_current_day_selected_bg_color' => 'c88195',
				    'datepicker_button_bg_color' => 'a5173f',
			    ),
			    'Day' => array(
				    'day_today_color' => 'a5173f',
				    'day_event_first_border_left' => 'ef1c51',
				    'day_event_second_border_left' => '1e0bab',
				    'day_event_third_border_left' => '00aeef',
				    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'fcd2dc',
				    'day_event_second_bg_color' => 'dbd7f2',
				    'day_event_third_bg_color' => 'b8e7f8',
			    ),
			    'Week' => array(
				    'week_current_day_bg_color' => 'a5173f',
				    'week_number_color' => 'a5173f',
				    'week_event_first_border_left' => 'ef1c51',
				    'week_event_second_border_left' => '1e0bab',
				    'week_event_third_border_left' => '00aeef',
				    'week_table_background_color' => 'ffffff',
				    'week_see_all_link_color' => 'a5173f',
				    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'fcd2dc',
				    'week_event_second_bg_color' => 'dbd7f2',
				    'week_event_third_bg_color' => 'b8e7f8',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => 'a5173f',
				    'month_table_background_color' => 'ffffff',
				    'month_table_weekend_columns_background_color' => 'f9f9f9',
				    'month_see_all_link_color' => 'a5173f',
				    'month_first_circle_bg_color' => 'ef1c51',
				    'month_second_circle_bg_color' => '1e0bab',
				    'month_third_circle_bg_color' => '00aeef',
				    'month_event_first_bg_color' => 'fcd2dc',
				    'month_event_second_bg_color' => 'dbd7f2',
				    'month_event_third_bg_color' => 'b8e7f8',
			    ),
			    'Year' => array(
				    'year_current_date_bg_color' => 'a5173f',
				    'year_title_color' => 'a5173f',
				    'year_current_month_color' => 'a5173f',
				    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => 'ef1c51',
				    'year_second_circle_bg_color' => '1e0bab',
				    'year_third_circle_bg_color' => '00aeef',
			    ),
		    ),
		    'Green' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => '578a51',
				    'sidebar_current_date_bg_color' => '578a51',
				    'sidebar_bg_color' => '343434',
				    'sidebar_first_circle_bg_color' => 'ff9e14',
				    'sidebar_second_circle_bg_color' => 'cdec3a',
				    'sidebar_third_circle_bg_color' => 'cfdaa2',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => '578a51',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => '578a51',
				    'datepicker_current_day_active_bg_color' => '578a51',
				    'datepicker_current_day_selected_bg_color' => 'a1ba9e',
				    'datepicker_button_bg_color' => '578a51',
			    ),
			    'Day' => array(
				    'day_today_color' => '578a51',
				    'day_event_first_border_left' => 'ff9e14',
				    'day_event_second_border_left' => 'cdec3a',
				    'day_event_third_border_left' => 'cfdaa2',
				    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'ffecd0',
				    'day_event_second_bg_color' => 'f5fbd8',
				    'day_event_third_bg_color' => 'f0f4e5',
			    ),
			    'Week' => array(
				    'week_current_day_bg_color' => '578a51',
				    'week_number_color' => '578a51',
				    'week_event_first_border_left' => 'ff9e14',
				    'week_event_second_border_left' => 'cdec3a',
				    'week_event_third_border_left' => 'cfdaa2',
				    'week_table_background_color' => 'ffffff',
				    'week_see_all_link_color' => '578a51',
				    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'ffecd0',
				    'week_event_second_bg_color' => 'f5fbd8',
				    'week_event_third_bg_color' => 'f0f4e5',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => '578a51',
				    'month_table_background_color' => 'ffffff',
				    'month_table_weekend_columns_background_color' => 'f9f9f9',
				    'month_see_all_link_color' => '578a51',
				    'month_first_circle_bg_color' => 'ff9e14',
				    'month_second_circle_bg_color' => 'cdec3a',
				    'month_third_circle_bg_color' => 'cfdaa2',
				    'month_event_first_bg_color' => 'ffecd0',
				    'month_event_second_bg_color' => 'f5fbd8',
				    'month_event_third_bg_color' => 'f0f4e5',
			    ),
			    'Year' => array(
				    'year_current_date_bg_color' => '578a51',
				    'year_title_color' => '578a51',
				    'year_current_month_color' => '578a51',
				    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => 'ff9e14',
				    'year_second_circle_bg_color' => 'cdec3a',
				    'year_third_circle_bg_color' => 'cfdaa2',
			    ),
		    ),
		    'Matt Purple' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => '663f52',
				    'sidebar_current_date_bg_color' => '663f52',
				    'sidebar_bg_color' => '29263a',
				    'sidebar_first_circle_bg_color' => 'f052b2',
				    'sidebar_second_circle_bg_color' => '01d3ac',
				    'sidebar_third_circle_bg_color' => '6d717c',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => '663f52',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => '663f52',
				    'datepicker_current_day_active_bg_color' => '663f52',
				    'datepicker_current_day_selected_bg_color' => 'a8959e',
				    'datepicker_button_bg_color' => '663f52',
			    ),
			    'Day' => array(
				    'day_today_color' => '663f52',
				    'day_event_first_border_left' => 'f052b2',
				    'day_event_second_border_left' => '01d3ac',
				    'day_event_third_border_left' => '6d717c',
				    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'fcdcf0',
				    'day_event_second_bg_color' => 'd9f7f1',
				    'day_event_third_bg_color' => 'ebe0e5',
			    ),
			    'Week' => array(
				    'week_current_day_bg_color' => '663f52',
				    'week_number_color' => '663f52',
				    'week_event_first_border_left' => 'f052b2',
				    'week_event_second_border_left' => '01d3ac',
				    'week_event_third_border_left' => '6d717c',
				    'week_table_background_color' => 'ffffff',
				    'week_see_all_link_color' => '663f52',
				    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'fcdcf0',
				    'week_event_second_bg_color' => 'd9f7f1',
				    'week_event_third_bg_color' => 'ebe0e5',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => '663f52',
				    'month_table_background_color' => 'ffffff',
				    'month_table_weekend_columns_background_color' => 'f9f9f9',
				    'month_see_all_link_color' => '663f52',
				    'month_first_circle_bg_color' => 'f052b2',
				    'month_second_circle_bg_color' => '01d3ac',
				    'month_third_circle_bg_color' => '6d717c',
				    'month_event_first_bg_color' => 'fcdcf0',
				    'month_event_second_bg_color' => 'd9f7f1',
				    'month_event_third_bg_color' => 'ebe0e5',
			    ),
			    'Year' => array(
				    'year_current_date_bg_color' => '663f52',
				    'year_title_color' => '663f52',
				    'year_current_month_color' => '663f52',
				    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => 'f052b2',
				    'year_second_circle_bg_color' => '01d3ac',
				    'year_third_circle_bg_color' => '6d717c',
			    ),
		    ),
		    'Matt Blue' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => '45698b',
				    'sidebar_current_date_bg_color' => '45698b',
				    'sidebar_bg_color' => '092741',
				    'sidebar_first_circle_bg_color' => '8fd36e',
				    'sidebar_second_circle_bg_color' => '4e9f96',
				    'sidebar_third_circle_bg_color' => 'e84c3d',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => '45698b',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => '45698b',
				    'datepicker_current_day_active_bg_color' => '45698b',
				    'datepicker_current_day_selected_bg_color' => '98aabb',
				    'datepicker_button_bg_color' => '45698b',
			    ),
			    'Day' => array(
				    'day_today_color' => '45698b',
				    'day_event_first_border_left' => '8fd36e',
				    'day_event_second_border_left' => '4e9f96',
				    'day_event_third_border_left' => 'e84c3d',
				    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'e9f6e2',
				    'day_event_second_bg_color' => 'dcecea',
				    'day_event_third_bg_color' => 'fadbd8',
			    ),
			    'Week' => array(
				    'week_current_day_bg_color' => '45698b',
				    'week_number_color' => '45698b',
				    'week_event_first_border_left' => '8fd36e',
				    'week_event_second_border_left' => '4e9f96',
				    'week_event_third_border_left' => 'e84c3d',
				    'week_table_background_color' => 'ffffff',
				    'week_see_all_link_color' => '45698b',
				    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'e9f6e2',
				    'week_event_second_bg_color' => 'dcecea',
				    'week_event_third_bg_color' => 'fadbd8',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => '45698b',
				    'month_table_background_color' => 'ffffff',
				    'month_table_weekend_columns_background_color' => 'f9f9f9',
				    'month_see_all_link_color' => '45698b',
				    'month_first_circle_bg_color' => '8fd36e',
				    'month_second_circle_bg_color' => '4e9f96',
				    'month_third_circle_bg_color' => 'e84c3d',
				    'month_event_first_bg_color' => 'e9f6e2',
				    'month_event_second_bg_color' => 'dcecea',
				    'month_event_third_bg_color' => 'fadbd8',
			    ),
			    'Year' => array(
				    'year_current_date_bg_color' => '45698b',
				    'year_title_color' => '45698b',
				    'year_current_month_color' => '45698b',
				    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => '8fd36e',
				    'year_second_circle_bg_color' => '4e9f96',
				    'year_third_circle_bg_color' => 'e84c3d',
			    ),
		    ),
		    'Yellow' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => 'f5dc5f',
				    'sidebar_current_date_bg_color' => 'f5dc5f',
				    'sidebar_bg_color' => '3a3935',
				    'sidebar_first_circle_bg_color' => 'ed145b',
				    'sidebar_second_circle_bg_color' => 'f9ad81',
				    'sidebar_third_circle_bg_color' => '00c495',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => 'f5dc5f',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => 'f5dc5f',
				    'datepicker_current_day_active_bg_color' => 'f5dc5f',
				    'datepicker_current_day_selected_bg_color' => 'f0e3a5',
				    'datepicker_button_bg_color' => 'f5dc5f',
			    ),
			    'Day' => array(
				    'day_today_color' => 'f5dc5f',
				    'day_event_first_border_left' => 'ed145b',
				    'day_event_second_border_left' => 'f9ad81',
				    'day_event_third_border_left' => '00c495',
				    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'fbd0de',
				    'day_event_second_bg_color' => 'feefe6',
				    'day_event_third_bg_color' => 'e3f6f2',
			    ),
			    'Week' => array(
				    'week_current_day_bg_color' => 'f5dc5f',
				    'week_number_color' => 'f5dc5f',
				    'week_event_first_border_left' => 'ed145b',
				    'week_event_second_border_left' => 'f9ad81',
				    'week_event_third_border_left' => '00c495',
				    'week_table_background_color' => 'ffffff',
				    'week_see_all_link_color' => 'f5dc5f',
				    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'fbd0de',
				    'week_event_second_bg_color' => 'feefe6',
				    'week_event_third_bg_color' => 'e3f6f2',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => 'f5dc5f',
				    'month_table_background_color' => 'ffffff',
				    'month_table_weekend_columns_background_color' => 'f9f9f9',
				    'month_see_all_link_color' => 'f5dc5f',
				    'month_first_circle_bg_color' => 'ed145b',
				    'month_second_circle_bg_color' => 'f9ad81',
				    'month_third_circle_bg_color' => '00c495',
				    'month_event_first_bg_color' => 'fbd0de',
				    'month_event_second_bg_color' => 'feefe6',
				    'month_event_third_bg_color' => 'e3f6f2',
			    ),
			    'Year' => array(
				    'year_current_date_bg_color' => 'f5dc5f',
				    'year_title_color' => 'f5dc5f',
				    'year_current_month_color' => 'f5dc5f',
				    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => 'ed145b',
				    'year_second_circle_bg_color' => 'f9ad81',
				    'year_third_circle_bg_color' => '00c495',
			    ),
		    ),
		    'Coral' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => 'ff5756',
				    'sidebar_current_date_bg_color' => 'ff5756',
				    'sidebar_bg_color' => '273238',
				    'sidebar_first_circle_bg_color' => '0059ff',
				    'sidebar_second_circle_bg_color' => '7fccc2',
				    'sidebar_third_circle_bg_color' => 'f49ac1',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => 'ff5756',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => 'ff5756',
				    'datepicker_current_day_active_bg_color' => 'ff5756',
				    'datepicker_current_day_selected_bg_color' => 'f5a1a0',
				    'datepicker_button_bg_color' => 'ff5756',
			    ),
			    'Day' => array(
				    'day_today_color' => 'ff5756',
				    'day_event_first_border_left' => '0059ff',
				    'day_event_second_border_left' => '7fccc2',
				    'day_event_third_border_left' => 'f49ac1',
				    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'ccdeff',
				    'day_event_second_bg_color' => 'e3f4f2',
				    'day_event_third_bg_color' => 'fee7f1',
			    ),
			    'Week' => array(
				    'week_current_day_bg_color' => 'ff5756',
				    'week_number_color' => 'ff5756',
				    'week_event_first_border_left' => '0059ff',
				    'week_event_second_border_left' => '7fccc2',
				    'week_event_third_border_left' => 'f49ac1',
				    'week_table_background_color' => 'ffffff',
				    'week_see_all_link_color' => 'ff5756',
				    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'ccdeff',
				    'week_event_second_bg_color' => 'e3f4f2',
				    'week_event_third_bg_color' => 'fee7f1',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => 'ff5756',
				    'month_table_background_color' => 'ffffff',
				    'month_table_weekend_columns_background_color' => 'f9f9f9',
				    'month_see_all_link_color' => 'ff5756',
				    'month_first_circle_bg_color' => '0059ff',
				    'month_second_circle_bg_color' => '7fccc2',
				    'month_third_circle_bg_color' => 'f49ac1',
				    'month_event_first_bg_color' => 'ccdeff',
				    'month_event_second_bg_color' => 'e3f4f2',
				    'month_event_third_bg_color' => 'fee7f1',
			    ),
			    'Year' => array(
				    'year_current_date_bg_color' => 'ff5756',
				    'year_title_color' => 'ff5756',
				    'year_current_month_color' => 'ff5756',
				    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => '0059ff',
				    'year_second_circle_bg_color' => '7fccc2',
				    'year_third_circle_bg_color' => 'f49ac1',
			    ),
		    ),
		    'Orange' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => 'f5a753',
				    'sidebar_current_date_bg_color' => 'f5a753',
				    'sidebar_bg_color' => '242323',
				    'sidebar_first_circle_bg_color' => '3cb878',
				    'sidebar_second_circle_bg_color' => 'fff200',
				    'sidebar_third_circle_bg_color' => 'ff5300',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => 'f5a753',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => 'f5a753',
				    'datepicker_current_day_active_bg_color' => 'f5a753',
				    'datepicker_current_day_selected_bg_color' => 'f0c99f',
				    'datepicker_button_bg_color' => 'f5a753',
			    ),
			    'Day' => array(
				    'day_today_color' => 'f5a753',
				    'day_event_first_border_left' => '3cb878',
				    'day_event_second_border_left' => 'fff200',
				    'day_event_third_border_left' => 'ff5300',
				    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'd8f1e4',
				    'day_event_second_bg_color' => 'fffccc',
				    'day_event_third_bg_color' => 'ffddcc',
			    ),
			    'Week' => array(
				    'week_current_day_bg_color' => 'f5a753',
				    'week_number_color' => 'f5a753',
				    'week_event_first_border_left' => '3cb878',
				    'week_event_second_border_left' => 'fff200',
				    'week_event_third_border_left' => 'ff5300',
				    'week_table_background_color' => 'ffffff',
				    'week_see_all_link_color' => 'f5a753',
				    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'd8f1e4',
				    'week_event_second_bg_color' => 'fffccc',
				    'week_event_third_bg_color' => 'ffddcc',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => 'f5a753',
				    'month_table_background_color' => 'ffffff',
				    'month_table_weekend_columns_background_color' => 'f9f9f9',
				    'month_see_all_link_color' => 'f5a753',
				    'month_first_circle_bg_color' => '3cb878',
				    'month_second_circle_bg_color' => 'fff200',
				    'month_third_circle_bg_color' => 'ff5300',
				    'month_event_first_bg_color' => 'd8f1e4',
				    'month_event_second_bg_color' => 'fffccc',
				    'month_event_third_bg_color' => 'ffddcc',
			    ),
			    'Year' => array(
				    'year_current_date_bg_color' => 'f5a753',
				    'year_title_color' => 'f5a753',
				    'year_current_month_color' => 'f5a753',
				    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => '3cb878',
				    'year_second_circle_bg_color' => 'fff200',
				    'year_third_circle_bg_color' => 'ff5300',
			    ),
		    ),
		    'Purple' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => '9b5085',
				    'sidebar_current_date_bg_color' => '9b5085',
				    'sidebar_bg_color' => '273238',
				    'sidebar_first_circle_bg_color' => 'fefcb3',
				    'sidebar_second_circle_bg_color' => '9fd6ae',
				    'sidebar_third_circle_bg_color' => 'e13368',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => '9b5085',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => '9b5085',
				    'datepicker_current_day_active_bg_color' => '9b5085',
				    'datepicker_current_day_selected_bg_color' => 'c39db8',
				    'datepicker_button_bg_color' => '9b5085',
			    ),
			    'Day' => array(
				    'day_today_color' => '9b5085',
				    'day_event_first_border_left' => 'fefcb3',
				    'day_event_second_border_left' => '9fd6ae',
				    'day_event_third_border_left' => 'e13368',
				    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'fffde4',
				    'day_event_second_bg_color' => 'e6faec',
				    'day_event_third_bg_color' => 'f9d6e1',
			    ),
			    'Week' => array(
				    'week_current_day_bg_color' => '9b5085',
				    'week_number_color' => '9b5085',
				    'week_event_first_border_left' => 'fefcb3',
				    'week_event_second_border_left' => '9fd6ae',
				    'week_event_third_border_left' => 'e13368',
				    'week_table_background_color' => 'ffffff',
				    'week_see_all_link_color' => '9b5085',
				    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'fffde4',
				    'week_event_second_bg_color' => 'e6faec',
				    'week_event_third_bg_color' => 'f9d6e1',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => '9b5085',
				    'month_table_background_color' => 'ffffff',
				    'month_table_weekend_columns_background_color' => 'f9f9f9',
				    'month_see_all_link_color' => '9b5085',
				    'month_first_circle_bg_color' => 'fefcb3',
				    'month_second_circle_bg_color' => '9fd6ae',
				    'month_third_circle_bg_color' => 'e13368',
				    'month_event_first_bg_color' => 'fffde4',
				    'month_event_second_bg_color' => 'e6faec',
				    'month_event_third_bg_color' => 'f9d6e1',
			    ),
			    'Year' => array(
				    'year_current_date_bg_color' => '9b5085',
				    'year_title_color' => '9b5085',
				    'year_current_month_color' => '9b5085',
				    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => 'fefcb3',
				    'year_second_circle_bg_color' => '9fd6ae',
				    'year_third_circle_bg_color' => 'e13368',
			    ),
		    ),
		    'Scampi' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => '646598',
				    'sidebar_current_date_bg_color' => '646598',
				    'sidebar_bg_color' => '282d30',
				    'sidebar_first_circle_bg_color' => 'a3d39c',
				    'sidebar_second_circle_bg_color' => 'a2a4ff',
				    'sidebar_third_circle_bg_color' => 'ef1c51',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => '646598',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => '646598',
				    'datepicker_current_day_active_bg_color' => '646598',
				    'datepicker_current_day_selected_bg_color' => 'a7a8c1',
				    'datepicker_button_bg_color' => '646598',
			    ),
			    'Day' => array(
				    'day_today_color' => '646598',
				    'day_event_first_border_left' => 'a3d39c',
				    'day_event_second_border_left' => 'a2a4ff',
				    'day_event_third_border_left' => 'ef1c51',
				    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'e3f1e0',
				    'day_event_second_bg_color' => 'ecedff',
				    'day_event_third_bg_color' => 'fcd2dc',
			    ),
			    'Week' => array(
				    'week_current_day_bg_color' => '646598',
				    'week_number_color' => '646598',
				    'week_event_first_border_left' => 'a3d39c',
				    'week_event_second_border_left' => 'a2a4ff',
				    'week_event_third_border_left' => 'ef1c51',
				    'week_table_background_color' => 'ffffff',
				    'week_see_all_link_color' => '646598',
				    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'e3f1e0',
				    'week_event_second_bg_color' => 'ecedff',
				    'week_event_third_bg_color' => 'fcd2dc',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => '646598',
				    'month_table_background_color' => 'ffffff',
				    'month_table_weekend_columns_background_color' => 'f9f9f9',
				    'month_see_all_link_color' => '646598',
				    'month_first_circle_bg_color' => 'a3d39c',
				    'month_second_circle_bg_color' => 'a2a4ff',
				    'month_third_circle_bg_color' => 'ef1c51',
				    'month_event_first_bg_color' => 'e3f1e0',
				    'month_event_second_bg_color' => 'ecedff',
				    'month_event_third_bg_color' => 'fcd2dc',
			    ),
			    'Year' => array(
				    'year_current_date_bg_color' => '646598',
				    'year_title_color' => '646598',
				    'year_current_month_color' => '646598',
				    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => 'a3d39c',
				    'year_second_circle_bg_color' => 'a2a4ff',
				    'year_third_circle_bg_color' => 'ef1c51',
			    ),
		    ),
		    'Light Matt Blue' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => '4f77a4',
				    'sidebar_current_date_bg_color' => '4f77a4',
				    'sidebar_bg_color' => '282d30',
				    'sidebar_first_circle_bg_color' => '92278f',
				    'sidebar_second_circle_bg_color' => '00bdf1',
				    'sidebar_third_circle_bg_color' => 'ff0',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => '4f77a4',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => '4f77a4',
				    'datepicker_current_day_active_bg_color' => '4f77a4',
				    'datepicker_current_day_selected_bg_color' => '9db1c7',
				    'datepicker_button_bg_color' => '4f77a4',
			    ),
			    'Day' => array(
				    'day_today_color' => '4f77a4',
				    'day_event_first_border_left' => '92278f',
				    'day_event_second_border_left' => '00bdf1',
				    'day_event_third_border_left' => 'ffff00',
				    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'e9d4e9',
				    'day_event_second_bg_color' => 'd0f4fd',
				    'day_event_third_bg_color' => 'ffffcc',
			    ),
			    'Week' => array(
				    'week_current_day_bg_color' => '4f77a4',
				    'week_number_color' => '4f77a4',
				    'week_event_first_border_left' => '92278f',
				    'week_event_second_border_left' => '00bdf1',
				    'week_event_third_border_left' => 'ffff00',
				    'week_table_background_color' => 'ffffff',
				    'week_see_all_link_color' => '4f77a4',
				    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'e9d4e9',
				    'week_event_second_bg_color' => 'd0f4fd',
				    'week_event_third_bg_color' => 'ffffcc',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => '4f77a4',
				    'month_table_background_color' => 'ffffff',
				    'month_table_weekend_columns_background_color' => 'f9f9f9',
				    'month_see_all_link_color' => '4f77a4',
				    'month_first_circle_bg_color' => '92278f',
				    'month_second_circle_bg_color' => '00bdf1',
				    'month_third_circle_bg_color' => 'ff0',
				    'month_event_first_bg_color' => 'e9d4e9',
				    'month_event_second_bg_color' => 'd0f4fd',
				    'month_event_third_bg_color' => 'ffffcc',
			    ),
			    'Year' => array(
				    'year_current_date_bg_color' => '4f77a4',
				    'year_title_color' => '4f77a4',
				    'year_current_month_color' => '4f77a4',
				    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => '92278f',
				    'year_second_circle_bg_color' => '00bdf1',
				    'year_third_circle_bg_color' => 'ff0',
			    ),
		    ),
		    'Turquoise' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => '1a9ba3',
				    'sidebar_current_date_bg_color' => '1a9ba3',
				    'sidebar_bg_color' => '282d30',
				    'sidebar_first_circle_bg_color' => 'fff78e',
				    'sidebar_second_circle_bg_color' => 'a3d39c',
				    'sidebar_third_circle_bg_color' => 'b5006b',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => '1a9ba3',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => '1a9ba3',
				    'datepicker_current_day_active_bg_color' => '1a9ba3',
				    'datepicker_current_day_selected_bg_color' => '82c3c7',
				    'datepicker_button_bg_color' => '1a9ba3',
			    ),
			    'Day' => array(
				    'day_today_color' => '1a9ba3',
				    'day_event_first_border_left' => 'fff78e',
				    'day_event_second_border_left' => 'a3d39c',
				    'day_event_third_border_left' => 'b5006b',
				    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'fffde8',
				    'day_event_second_bg_color' => 'edf6eb',
				    'day_event_third_bg_color' => 'f0cce1',
			    ),
			    'Week' => array(
				    'week_current_day_bg_color' => '1a9ba3',
				    'week_number_color' => '1a9ba3',
				    'week_event_first_border_left' => 'fff78e',
				    'week_event_second_border_left' => 'a3d39c',
				    'week_event_third_border_left' => 'b5006b',
				    'week_table_background_color' => 'ffffff',
				    'week_see_all_link_color' => '1a9ba3',
				    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'fffde8',
				    'week_event_second_bg_color' => 'edf6eb',
				    'week_event_third_bg_color' => 'f0cce1',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => '1a9ba3',
				    'month_table_background_color' => 'ffffff',
				    'month_table_weekend_columns_background_color' => 'f9f9f9',
				    'month_see_all_link_color' => '1a9ba3',
				    'month_first_circle_bg_color' => 'fff78e',
				    'month_second_circle_bg_color' => 'a3d39c',
				    'month_third_circle_bg_color' => 'b5006b',
				    'month_event_first_bg_color' => 'fffde8',
				    'month_event_second_bg_color' => 'edf6eb',
				    'month_event_third_bg_color' => 'f0cce1',
			    ),
			    'Year' => array(
				    'year_current_date_bg_color' => '1a9ba3',
				    'year_title_color' => '1a9ba3',
				    'year_current_month_color' => '1a9ba3',
				    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => 'fff78e',
				    'year_second_circle_bg_color' => 'a3d39c',
				    'year_third_circle_bg_color' => 'b5006b',
			    ),
		    ),

		    'Dark Matt Green' => array(
			    'Sidebar' => array(
				    'sidebar_header_bg_color' => '299a8b',
				    'sidebar_current_date_bg_color' => '299a8b',
				    'sidebar_bg_color' => '282d30',
				    'sidebar_first_circle_bg_color' => '839d91',
				    'sidebar_second_circle_bg_color' => 'aba6d8',
				    'sidebar_third_circle_bg_color' => 'ec008c',
			    ),
			    'Menu Bar' => array(
				    'active_button_bg_color' => '299a8b',
				    'view_button_bg_color' => 'ebebeb',
				    'view_button_hover_bg_color' => '299a8b',
				    'datepicker_current_day_active_bg_color' => '1a9ba3',
				    'datepicker_current_day_selected_bg_color' => '82c3c7',
				    'datepicker_button_bg_color' => '299a8b',
			    ),
			    'Day' => array(
				    'day_today_color' => '299a8b',
				    'day_event_first_border_left' => '839d91',
				    'day_event_second_border_left' => 'aba6d8',
				    'day_event_third_border_left' => 'ec008c',
				    'day_table_weekend_columns_background_color' => 'f9f9f9',
				    'day_event_first_bg_color' => 'dde9e4',
				    'day_event_second_bg_color' => 'eae8f6',
				    'day_event_third_bg_color' => 'fbcce8',
			    ),
			    'Week' => array(
				    'week_current_day_bg_color' => '299a8b',
				    'week_number_color' => '299a8b',
				    'week_event_first_border_left' => '839d91',
				    'week_event_second_border_left' => 'aba6d8',
				    'week_event_third_border_left' => 'ec008c',
				    'week_table_background_color' => 'ffffff',
				    'week_see_all_link_color' => '299a8b',
				    'week_table_weekend_columns_background_color' => 'f9f9f9',
				    'week_event_first_bg_color' => 'dde9e4',
				    'week_event_second_bg_color' => 'eae8f6',
				    'week_event_third_bg_color' => 'fbcce8',
			    ),
			    'Month' => array(
				    'month_current_date_bg_color' => '299a8b',
				    'month_table_background_color' => 'ffffff',
				    'month_table_weekend_columns_background_color' => 'f9f9f9',
				    'month_see_all_link_color' => '299a8b',
				    'month_first_circle_bg_color' => '839d91',
				    'month_second_circle_bg_color' => 'aba6d8',
				    'month_third_circle_bg_color' => 'ec008c',
				    'month_event_first_bg_color' => 'dde9e4',
				    'month_event_second_bg_color' => 'eae8f6',
				    'month_event_third_bg_color' => 'fbcce8',
			    ),
			    'Year' => array(
				    'year_current_date_bg_color' => '299a8b',
				    'year_title_color' => '299a8b',
				    'year_current_month_color' => '299a8b',
				    'year_table_days_background_color' => 'ffffff',
				    'year_first_circle_bg_color' => '839d91',
				    'year_second_circle_bg_color' => 'aba6d8',
				    'year_third_circle_bg_color' => 'ec008c',
			    ),
		    ),
        );

		$theme_settings = new ThemeSettings();
		set_time_limit(100);

		foreach ($defaultThemesOptions as $key => $defaultThemesOption){

			$theme = new Theme( array( 'name' => $key ) );
			$theme_name = $theme->get_name();

			if($theme_name === $key){
				$theme_id = $theme->get_id();

				foreach ($defaultThemesOption as $key_type => $themesOption){
					foreach ($themesOption as $key_option => $value_option){
						$theme_settings->set_theme_settings($theme_id, $key_type, $key_option, $value_option);
					}
				}
			}
		}
	}
}